version: '3.4'

networks:
  lingarr:
    external: true

services:
  Lingarr.Client:
    image: ${DOCKER_REGISTRY-}lingarrclient
    container_name: Lingarr.Client
    build:
      context: ./Lingarr.Client/
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    volumes:
      - ./Lingarr.Client:/app:rw
      - ./Lingarr.Client/node_modules:/app/node_modules
    tty: true
    command: /bin/sh -c "npm install && npm run dev"
    networks:
      - lingarr

  Lingarr.Server:
    container_name: Lingarr.Server
    image: ${DOCKER_REGISTRY-}lingarrserver
    build:
      context: .
      dockerfile: Lingarr.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9877:8080"
    networks:
      - lingarr

  LibreTranslate:
    image: ${DOCKER_REGISTRY-}libretranslate
    build:
      context: .
      dockerfile: Dockerfile.libretranslate
    container_name: LibreTranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - lingarr
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']