name: Bug Report
description: Create a report to help us improve Lingarr
title: '[BUG] Provide a descriptive title'
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: "Provide a detailed description of the issue, steps to reproduce, and expected vs actual behavior"
      placeholder: "Describe the issue here..."
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Screenshots or Additional Context
      description: Provide any additional context and screenshots, docker compose configurations here to help us solve this issue.
    validations:
      required: false

  - type: checkboxes
    id: not-llm
    attributes:
      label: Human written confirmation
      options:
        - label: I confirm this issue was written by me and not generated by an LLM or AI assistant.
          required: true